// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChzIZ52X27zYrhiEPX8OzH_ZRBrtcjmsg',
    appId: '1:745490602639:web:36cddd21eedf3fc212aefa',
    messagingSenderId: '745490602639',
    projectId: 'note-775c8',
    authDomain: 'note-775c8.firebaseapp.com',
    storageBucket: 'note-775c8.appspot.com',
    measurementId: 'G-GE18R5XWB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Y9uiu0p6reeKfPOMHL_NvcSQ_2mga3M',
    appId: '1:745490602639:android:ebac3edc62ad8bfe12aefa',
    messagingSenderId: '745490602639',
    projectId: 'note-775c8',
    storageBucket: 'note-775c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_dT0R3meklQ-J65EPHj4T5Sn3CDoLPYA',
    appId: '1:379191347602:ios:f5e5d6392866dce55ed94b',
    messagingSenderId: '379191347602',
    projectId: 'note-1496b',
    storageBucket: 'note-1496b.appspot.com',
    iosBundleId: 'com.example.myDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_dT0R3meklQ-J65EPHj4T5Sn3CDoLPYA',
    appId: '1:379191347602:ios:f5e5d6392866dce55ed94b',
    messagingSenderId: '379191347602',
    projectId: 'note-1496b',
    storageBucket: 'note-1496b.appspot.com',
    iosBundleId: 'com.example.myDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCblvRq5cPXJ7sRjA-t1pHcoof8D_-okOg',
    appId: '1:379191347602:web:76136dcb6a598a875ed94b',
    messagingSenderId: '379191347602',
    projectId: 'note-1496b',
    authDomain: 'note-1496b.firebaseapp.com',
    storageBucket: 'note-1496b.appspot.com',
    measurementId: 'G-NTTB1H897K',
  );
}